### ISSUE TITLE
The guide disallows deep linking from abroad

### ISSUE THREAD

**Issue by mushon** [OpenBudget/open-budget-frontend#321] opened 2015-11-19 09:20 UTC
deep links jump to the homepage

**Comment by mushon** [comment] 2015-11-23 13:17
Apparently this happens to Israeli users too on their first visit to the site. It definitely looks like something that the guide is doing. @akariv let's make this a priority

**Comment by Bnaya** [comment] 2015-11-23 14:46
Can you add repro link?

**Comment by mushon** [comment] 2015-11-23 17:36
@prsnca will look into it

**Comment by prsnca** [comment] 2015-11-23 21:19
I have investigated this issue tonight.. the root of the problem is that on every page load (not only the main page), the tour is loaded. The bootstrap-tour checks if the tour was already ended (by checking the localStorage key 'tour_main-end') and does not jump to the tour if this key is found. 
A possible solution is to not start the tour automatically, and to add a pre-tour tooltip which will serve instead of the first step. 
@akariv - what is your opinion?

**Comment by mushon** [comment] 2015-11-24 05:37
I think this was accidentally closed

**Comment by akariv** [comment] 2015-11-24 07:45
Yes - good idea.
in case we're not opening the main page, we should suggest the tour and
allow it to be skipped so that the user remains in the original page she
was directed to.

**Comment by mushon** [comment] 2015-12-14 20:12
@dannycodes @adierteschik look at that too

**Comment by mushon** [comment] 2015-12-14 20:33
@Bnaya it's here

**Comment by Bnaya** [comment] 2015-12-14 21:01
repo link for reference 
http://localhost:9000/#main//2015/main?focusOn=001501

**Comment by Bnaya** [comment] 2015-12-15 00:37
I think i've managed to fix it with
https://github.com/OpenBudget/open-budget-frontend/compare/fix-tour-redirect?expand=1
Check it at
http://obudget2.bnaya.net/#main//2014/main?focusOn=008405

**Comment by Bnaya** [comment] 2015-12-15 08:17
fixed in #329

**Closed by Bnaya** 2015-12-15 08:17 UTC
Labels: bug
